global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'console'
  routes:
    - match:
        alertname: NodeExporterDown
      receiver: console
    - match:
        alertname: NodeExporterDownDev
      receiver: dev
    - match:
        alertname: NodeExporterDownInfra
      receiver: infra

receivers:
  - name: 'console'
  - name: 'dev'
  - name: 'infra'
