{
 "title": "Système & App Demo",
 "description": "TP Métrologie - SALAÜN Kerrian",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Taux de requêtes HTTP App pour 1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge CPU App",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(simulated_cpu_percent[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Système",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "  100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}